version: '3.8'

services:
  backend:
    build:
      context: .  # Path to the project root directory
      dockerfile: backend/Dockerfile
    ports:
      - "3000:3000"  # Expose port 3000 of the container to port 3000 on your machine
    environment:
      - NODE_ENV=development
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"  # Expose port 80 of the container to port 80 on your machine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf  # Mount the custom Nginx config
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
